### ISSUE TITLE
Put up an appropriate OSS License

### ISSUE THREAD

**Issue by najibninaba** [kelaberetiv/aiap-field-guide#6]
Although our AIAP Field Guide is open, it's not explicitly stated. Recommend we choose something from here: https://choosealicense.com/. Typically for non-code assets, an appropriate Creative Commons License is used whereas MIT License is used for code.

**Comment by jeannefukumaru** [comment]
Need to check with Laurence which license is appropriate. Ken may have some ideas from the TagUI project
